#alias ssh="kitty +kitten ssh"
#export PATH=$HOME/.fpath/bin:$PATH:$HOME/.emacs.d/bin:$PATH:$HOME/elixir-ls/release
export PATH=$HOME/.fpath/bin:$PATH:$HOME/.emacs.d/bin
export PATH=$PATH:/home/blaeni/.asdf/installs/nodejs/10.16.0/.npm/bin
export ANDROID_HOME=$HOME/Android/Sdk
export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/tools/bin
export PATH=$PATH:$ANDROID_HOME/platform-tools
alias compr="killall compton && compton -b"
alias l="exa"
alias lt="exa --tree"
alias ltl="exa --tree -l"
alias ltla="exa --tree -la"
alias ll="exa -l"
alias la="exa -a"
alias lla="exa -la"
alias lock="xscreensaver-command -lock"
alias android-reverse="adb -s EHT7N19321006753 reverse tcp:8081 tcp:8081"
alias android-taxi="adb -s EHT7N19321006753 reverse tcp:8080 tcp:8080"
alias android-menu="adb shell input keyevent 82"
